spring:
  application:
    name: unnie
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    resources:
      cache:
        cachecontrol:
          no-store: true


  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: WinnerHikariPool
      minimum-idle: 5
      maximum-pool-size: 10

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 2s
      password: ${SPRING_DATA_REDIS_PASSWORD:}

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# --- 애플리케이션 고유 설정 ---
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-spring.xml

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: ${MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED:true}
  health:
    redis:
      enabled: ${MANAGEMENT_HEALTH_REDIS_ENABLED:true}

  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: health,info

server:
  port: ${SERVER_PORT:5000}
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    path: /error

upload:
  path: ${user.dir}\src\main\resources\static\upload\

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

naver:
  ocr:
    url: ${NAVER_OCR_URL:}
    secret: ${NAVER_OCR_SECRET:}
  geocoding:
    url: "https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode"
    clientId: ${NAVER_GEOCODING_CLIENT_ID:}
    clientSecret: ${NAVER_GEOCODING_CLIENT_SECRET:}

openai:
  api:
    key: ${OPENAI_API_KEY:}

coolsms:
  api:
    key: ${COOLSMS_API_KEY:}
    secret: ${COOLSMS_API_SECRET:}
    number: ${COOLSMS_API_NUMBER:}

public-api:
  business:
    base-url: "http://api.odcloud.kr/api/nts-businessman/v1/validate?serviceKey="
    service-key: ${PUBLIC_API_SERVICE_KEY:}

youtube:
  api:
    key: ${YOUTUBE_API_KEY:}

toss:
  secret-key: ${TOSS_SECRET_KEY:}
  client-key: ${TOSS_CLIENT_KEY:}
  success-url: ${TOSS_SUCCESS_URL:}
  fail-url: ${TOSS_FAIL_URL:}


