spring:
  application:
    name: unnie
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    resources:
      cache:
        cachecontrol:
          no-store: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/unnie?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: WinnerHikariPool
      minimum-idle: 5
      maximum-pool-size: 10

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD:}

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-spring.xml

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'

server:
  port: 8111
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    path: /error

upload:
  path: ${user.dir}\src\main\resources\static\upload\

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

