name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-2
  EB_APPLICATION_NAME: unnieuttae        # ← EB 콘솔의 Application 이름과 정확히 일치
  EB_ENVIRONMENT_NAME: unnieuttae-prod    # ← EB 콘솔의 Environment 이름과 정확히 일치

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:           # ★ OIDC 필수
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build WAR
        run: ./gradlew clean bootWar

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<GitHubOIDC-Role>
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name:  ${{ env.EB_APPLICATION_NAME }}
          environment_name:  ${{ env.EB_ENVIRONMENT_NAME }}
          region:            ${{ env.AWS_REGION }}
          version_label:     ${{ github.sha }}
          deployment_package: build/libs/unnie-0.0.1-SNAPSHOT.war
