name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: unnie-app-repo
  ECS_CLUSTER: unnie-cluster
  ECS_SERVICE: unnie-service
  CONTAINER_NAME: unnie-container

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Secrets
        run: |
          echo "Access Key ID Exists? ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "Secret Access Key Exists? ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # bootJar가 있으면 그걸, 없으면 build (test 태스크가 없어도 에러 안 나게 방어)
      - name: Build application
        shell: bash
        run: |
          set -e
          if ./gradlew tasks --all | grep -qE '(^|[:[:space:]])bootJar[[:space:]]'; then
            echo ">> bootJar detected. Building with bootJar"
            ./gradlew bootJar --no-daemon
          else
            echo ">> bootJar not found. Using build (skip test if present)"
            if ./gradlew tasks --all | grep -qE '(^|[:[:space:]])test[[:space:]]'; then
              ./gradlew build -x test --no-daemon
            else
              ./gradlew build --no-daemon
            fi
          fi
          echo "== built files =="
          ls -alh **/build/libs || true

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          set -e
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ github.sha }} .
          docker tag  ${{ env.ECR_REPOSITORY }}:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          echo "image=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest" >> $GITHUB_OUTPUT

      - name: Force new deployment on ECS service (use latest image)
        run: |
          aws ecs update-service \
            --cluster "${{ env.ECS_CLUSTER }}" \
            --service "${{ env.ECS_SERVICE }}" \
            --force-new-deployment \
            --region "${{ env.AWS_REGION }}"
