name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches: [ main ]
env:
  AWS_REGION: ap-northeast-2
  EB_APPLICATION_NAME: unnieuttae
  EB_ENVIRONMENT_NAME: unnieuttae-prod
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew bootWar -x test --no-daemon
      - name: Find WAR path
        id: findwar
        shell: bash
        run: |
          set -e
          war=$(ls -1 build/libs/*.war 2>/dev/null | grep -v 'plain.war' | head -n1)
          [ -z "$war" ] && { echo "No WAR found"; exit 1; }
          echo "war=$war" >> "$GITHUB_OUTPUT"
      - name: Create ZIP bundle
        shell: bash
        run: |
          set -eux
          rm -rf build/deployment eb-bundle.zip
          mkdir -p build/deployment
          cp "${{ steps.findwar.outputs.war }}" build/deployment/application.war
          cp -r .platform build/deployment/.platform
          chmod -R +x build/deployment/.platform/hooks || true
          (cd build/deployment && zip -r ../../eb-bundle.zip .)
          unzip -l eb-bundle.zip
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name: ${{ env.EB_APPLICATION_NAME }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          region: ${{ env.AWS_REGION }}
          version_label: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
          use_existing_version_if_available: true
          deployment_package: eb-bundle.zip
          wait_for_deployment: false
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
