name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-2
  EB_APPLICATION_NAME: unnieuttae
  EB_ENVIRONMENT_NAME: unnieuttae-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build WAR
        run: ./gradlew bootWar -x test

      - name: Show build artifacts
        run: ls -al build/libs



      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name:  ${{ env.EB_APPLICATION_NAME }}
          environment_name:  ${{ env.EB_ENVIRONMENT_NAME }}
          region:            ${{ env.AWS_REGION }}
          version_label:     ${{ github.sha }}
          deployment_package: build/libs/*.war
          aws_access_key:    ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key:    ${{ secrets.AWS_SECRET_ACCESS_KEY }}
